# Syncing CSV data to the SQLite DB
<hr>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import requests
import seaborn as sns
from sklearn.linear_model import LinearRegression
import Data_Functions as dh
import DataHandler as dbh

## Setting up Database Handler
<hr>

In [2]:
db = dbh.Database_Handler()

### Data handler stores game results as: <br>
Game Version, Date, Time Survived, Score
<br><br>
### Data handler stores game end data as: <br>
Date, Collision Object, Time Object Spawned, Enemies Alive
<br><br>
### Data handler stores powerups spawned as: <br>
Date, Powerup (name), Time Spawned, Time Activated, Time Effect Ended, Times Player Hit

In [3]:
gr_df = dh.read_results()

ged_df = dh.read_game_end_data()

gr_powerups = dh.read_powerup_data()

### Changes required for Game Results and Game End Data to become GameRun: <br>
<ul>
    <li>add score_per_second column</li>
    <li>merge gr_df and ged_df</li>
</ul>

### Changes requred for Powerup data to become PowerupsSpawned: <br>
<ul>
    <li>Add PowerupID for each Powerup (name)</li>
    <li>Remove Powerup (name)</li>
</ul>

## Preparing Game Results and Game End Data 
<hr>

In [4]:
gr_df["Score Per Second"] = gr_df["Score"] / gr_df["Time Survived"]

In [5]:
game_run_df = pd.merge(gr_df, ged_df, on="Date", how="left")
game_run_df = game_run_df.replace({pd.NA: None})

In [6]:
game_run_df

,Game Version,Time Survived,Score,Survival Group,Score Group,Score Per Second,Collision Object,Time Object Spawned,Enemies Alive
Date,,,,,,,,,
2026-08-11 22:02:53.976116,2026-08-10 23:55:20.054130,10.757392,260,10 < 30,100 < 499,24.169427,None,NaN,NaN
2026-08-11 22:03:49.405594,2026-08-10 23:55:20.054130,24.408522,933,10 < 30,500 < 999,38.224355,None,NaN,NaN
2026-08-11 22:07:52.788656,2026-08-10 23:55:20.054130,1.700332,31,0 < 5,0 < 99,18.231729,None,NaN,NaN
2026-08-11 22:08:16.921228,2026-08-10 23:55:20.054130,12.781978,340,10 < 30,100 < 499,26.599951,None,NaN,NaN
2026-08-11 22:09:49.791919,2026-08-10 23:55:20.054130,0.995767,17,0 < 5,0 < 99,17.072269,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2026-09-15 18:41:42.283207,2026-09-15 16:50:42.768660,17.247342,528,10 < 30,500 < 999,30.613412,Cube,1.587924,21.0
2026-09-15 18:42:00.192944,2026-09-15 16:50:42.768660,15.583310,449,10 < 30,100 < 499,28.812877,Cube,13.362484,21.0
2026-09-16 19:23:16.080657,2026-09-13 20:34:46.245973,2.950675,53,0 < 5,0 < 99,17.96199,Cube,1.924126,20.0
2026-09-16 19:24:26.477879,2026-09-13 20:34:46.245973,11.260231,276,10 < 30,100 < 499,24.511043,Cube,1.081997,20.0
2026-09-16 19:25:17.348551,2026-09-13 20:34:46.245973,30.755195,1298,30 < 60,1000 < 4999,42.204252,Cube,0.639811,21.0

## Preparing Powerups Data for PowerupsSpawned
<hr>

In [7]:
gr_powerups["PowerupID"] = gr_powerups["Powerup"].apply(db.get_powerup)

In [8]:
gr_powerups

,Powerup,Time Spawned,Time Activated,Time Effect Ended,Times Player Hit,PowerupID
Date,,,,,,
2026-08-20 19:53:15.689284,Eat_Enemy_Powerup,22.549473,25.925230,30.938932,NaN,2
2026-08-20 19:53:15.689284,Eat_Enemy_Powerup,45.070239,45.870412,50.875540,NaN,2
2026-08-20 19:53:15.689284,Score_Increase_Powerup,15.043289,15.925274,20.856675,NaN,1
2026-08-20 19:53:15.689284,Score_Increase_Powerup,30.052839,30.883667,35.842999,NaN,1
2026-08-20 19:53:15.689284,Temp_Change_Colour_Powerup,7.528527,NaN,NaN,NaN,3
...,...,...,...,...,...,...
2026-09-16 19:24:26.477879,Temp_Change_Colour_Powerup,7.515464,11.126915,NaN,7.0,3
2026-09-16 19:25:17.348551,Eat_Enemy_Powerup,15.019709,15.893578,20.899181,5.0,2
2026-09-16 19:25:17.348551,Eat_Enemy_Powerup,22.524488,24.291256,29.299025,3.0,2
2026-09-16 19:25:17.348551,Temp_Change_Colour_Powerup,7.506726,9.709999,14.689512,4.0,3
2026-09-16 19:25:17.348551,Temp_Change_Colour_Powerup,30.035182,NaN,NaN,NaN,3

## Pre insert db sizes
<hr>
GameRun

In [9]:
before_gr_count = db.get_GameRun_count()
before_gr_count

66

PowerupsSpawned

In [10]:
before_ps_count = db.get_PowerupsSpawned_count()
before_ps_count

34

## Adding data frames to db
<hr>

In [11]:
next(game_run_df.itertuples())

Pandas(Index=Timestamp('2026-08-11 22:02:53.976116'), _1=Timestamp('2026-08-10 23:55:20.054130'), _2=10.757391929626465, Score=np.int64(260), _4='10 < 30', _5='100 < 499', _6=24.169427097282316, _7=None, _8=nan, _9=nan)

In [12]:
cur = db.db.cursor()
text = "INSERT OR IGNORE INTO GameRun (date, game_version_time, time_survived, score, score_per_second, collision_object, time_object_spawned, enemies_alive) VALUES "
for row in game_run_df.itertuples():
    text += f"('{row.Index}', '{row._1}', '{row._2}', '{row.Score}', " 
    text += f"{'NULL' if row._6 is None else row._6}, '{'NULL' if row._7 is None else row._7}', '{'NULL' if pd.isna(row._8) else row._8}', '{'NULL' if pd.isna(row._9) else row._9}'), "
text = text[:-2]
text = text.replace("'NULL'", "NULL")
#print(text)
cur.execute(text)
db.db.commit()

In [13]:
next(gr_powerups.itertuples())

Pandas(Index=Timestamp('2026-08-20 19:53:15.689284'), Powerup='Eat_Enemy_Powerup', _2=22.54947328567505, _3=25.925230264663696, _4=30.938931703567505, _5=nan, PowerupID=2)

In [14]:
text = "INSERT OR IGNORE INTO PowerupsSpawned (date, powerupID, time_spawned, time_activated, time_ended) VALUES "
for row in gr_powerups.itertuples():
    text += f"('{row.Index}', '{row.PowerupID}', '{row._2}', '{'NULL' if pd.isna(row._3) else row._3}', '{'NULL' if pd.isna(row._4) else row._4}'), "
text = text[:-2]
text = text.replace("'NULL'", "NULL")
#print(text)
cur.execute(text)
db.db.commit()

INSERT OR IGNORE INTO PowerupsSpawned (date, powerupID, time_spawned, time_activated, time_ended) VALUES ('2026-08-20 19:53:15.689284', '2', '22.54947328567505', '25.925230264663696', '30.938931703567505'), ('2026-08-20 19:53:15.689284', '2', '45.07023859024048', '45.87041187286377', '50.87553954124451'), ('2026-08-20 19:53:15.689284', '1', '15.043289184570312', '15.925274133682253', '20.856674671173096'), ('2026-08-20 19:53:15.689284', '1', '30.052839279174805', '30.883666515350345', '35.84299850463867'), ('2026-08-20 19:53:15.689284', '3', '7.528526544570923', NULL, NULL), ('2026-08-20 19:53:15.689284', '3', '37.566134452819824', '42.25059151649475', '47.2196044921875'), ('2026-08-20 19:53:15.689284', '3', '52.58163619041443', '54.18901181221008', NULL), ('2026-08-20 19:57:41.418609', '1', '15.034730911254885', '18.964815378189087', '23.95594358444214'), ('2026-08-20 19:57:41.418609', '3', '7.519971609115601', '9.221335649490356', '14.218408584594728'), ('2026-08-20 19:57:41.418609', '3', '22.53540825843811', '24.892029762268063', '29.83845067024231'), ('2026-08-20 19:57:41.418609', '3', '30.0389142036438', '31.751976251602173', '36.74937844276428'), ('2026-08-20 19:57:41.418609', '3', '37.54211497306824', '39.2375078201294', '44.22831654548645'), ('2026-08-20 19:57:41.418609', '3', '45.04768586158752', '47.46905779838562', '52.409143924713135'), ('2026-08-20 19:57:41.418609', '3', '52.562150716781616', '53.71859121322632', '58.65630531311035'), ('2026-08-20 19:57:41.418609', '3', '60.06538343429565', '61.28846025466919', NULL), ('2026-08-20 19:58:06.768919', '2', '7.52545690536499', '13.874351501464844', NULL), ('2026-08-20 19:58:50.274679', '2', '30.05278706550598', '30.874716758728027', NULL), ('2026-08-20 19:58:50.274679', '1', '7.532514333724976', '9.045320749282835', '13.969177722930908'), ('2026-08-20 19:58:50.274679', '1', '22.54829978942871', '23.857689142227173', '28.826716661453247'), ('2026-08-20 19:58:50.274679', '3', '15.034379243850708', '17.442066192626953', '22.4401330947876'), ('2026-08-20 20:01:49.515100', '2', '15.02064061164856', '18.577996492385864', '23.579395532608032'), ('2026-08-20 20:01:49.515100', '2', '22.52544522285461', '26.52169442176819', '31.53260016441345'), ('2026-08-20 20:01:49.515100', '1', '30.03010654449463', '33.012418031692505', '37.93439722061157'), ('2026-08-20 20:01:49.515100', '1', '45.03463196754456', '45.790339946746826', '50.76046347618103'), ('2026-08-20 20:01:49.515100', '1', '52.547847270965576', '56.913769006729126', '61.8547568321228'), ('2026-08-20 20:01:49.515100', '3', '7.517868518829346', '9.633057832717896', '14.557698726654053'), ('2026-08-20 20:01:49.515100', '3', '37.53334951400757', '39.96886944770813', '44.896515130996704'), ('2026-08-20 20:01:49.515100', '3', '60.05434322357178', '61.75687170028687', '66.69714999198914'), ('2026-08-20 20:01:49.515100', '3', '67.56626081466675', '69.41361284255981', '74.35946846008301'), ('2026-08-20 20:01:49.515100', '3', '75.07025289535522', NULL, NULL), ('2026-08-22 20:58:15.128028', '3', '7.518946409225464', NULL, NULL), ('2026-08-22 22:01:53.501948', '2', '7.511194944381714', NULL, NULL), ('2026-08-22 22:01:53.501948', '1', '15.020082712173462', NULL, NULL), ('2026-08-22 22:39:29.947789', '1', '15.02556324005127', NULL, NULL), ('2026-08-22 22:39:29.947789', '3', '7.520730972290039', NULL, NULL), ('2026-08-22 22:39:29.947789', '3', '22.533981561660767', NULL, NULL), ('2026-08-22 22:43:03.444771', '2', '15.019893646240234', '16.10815453529358', NULL), ('2026-08-22 22:43:03.444771', '1', '7.512535333633423', '9.357385396957396', '14.322061538696287'), ('2026-08-23 16:56:48.705298', '1', '7.517389297485352', '11.331432342529297', '16.33541464805603'), ('2026-08-23 16:56:48.705298', '1', '37.56002163887024', '42.1228404045105', NULL), ('2026-08-23 16:56:48.705298', '3', '15.02923846244812', '17.503847122192383', '22.4312961101532'), ('2026-08-23 16:56:48.705298', '3', '22.540314197540283', '23.44137454032898', '28.397599935531616'), ('2026-08-23 16:56:48.705298', '3', '30.053917169570923', '30.942603826522827', '35.88129258155823'), ('2026-08-23 16:57:39.821401', '1', '15.030473470687866', '20.40591859817505', '25.415951013565063'), ('2026-08-23 16:57:39.821401', '3', '7.52192759513855', '11.868829727172852', '16.81658625602722'), ('2026-08-23 16:57:39.821401', '3', '22.54085612297058', '23.72004747390747', NULL), ('2026-08-23 16:58:16.266367', '2', '22.52804470062256', '23.784536361694336', NULL), ('2026-08-23 16:58:16.266367', '1', '15.023862838745115', '21.200196504592896', NULL), ('2026-08-23 16:58:16.266367', '3', '7.51685905456543', NULL, NULL), ('2026-08-23 17:32:50.567710', '2', '7.515516519546509', '7.537200450897217', NULL), ('2026-08-23 17:33:41.452879', '2', '15.029919385910034', '16.304851055145264', NULL), ('2026-08-23 17:35:58.867896', '3', '7.518712520599365', '8.746586561203003', NULL), ('2026-08-23 17:39:13.616564', '3', '7.525634765625', NULL, NULL), ('2026-08-23 17:40:11.279252', '2', '7.524426937103271', '9.19981837272644', '14.202664136886597'), ('2026-08-23 17:40:11.279252', '2', '30.05021572113037', '31.07688331604004', NULL), ('2026-08-23 17:40:11.279252', '3', '22.545827388763428', '23.38026070594788', '28.3641996383667'), ('2026-08-23 17:41:49.185993', '2', '22.53742837905884', '24.1506187915802', '29.154897928237915'), ('2026-08-23 17:41:49.185993', '2', '37.56241321563721', '38.28401064872742', NULL), ('2026-08-23 17:41:49.185993', '3', '7.520102977752685', '9.893741130828856', '14.88609504699707'), ('2026-08-23 17:43:55.902918', '2', '15.025063037872314', '15.930984258651732', '20.94414710998535'), ('2026-08-23 17:43:55.902918', '2', '45.04213643074036', '45.87804317474365', NULL), ('2026-08-23 17:43:55.902918', '1', '7.516201972961426', '10.100498676300049', '15.102223634719849'), ('2026-08-23 17:43:55.902918', '1', '22.53202533721924', '23.770854473114014', '28.708885431289676'), ('2026-08-23 17:43:55.902918', '1', '30.03385281562805', '34.67034840583801', '39.67678642272949'), ('2026-08-23 17:43:55.902918', '3', '37.53844046592712', '40.16074848175049', '45.15093684196472'), ('2026-08-23 18:02:31.527831', '2', '22.534096002578732', '23.24006128311157', '28.25472211837769'), ('2026-08-23 18:02:31.527831', '2', '30.04603147506714', '33.30606746673584', '38.32118535041809'), ('2026-08-23 18:02:31.527831', '2', '75.0872220993042', '75.85708141326904', NULL), ('2026-08-23 18:02:31.527831', '1', '52.57697010040283', '55.32127213478088', '60.324939489364624'), ('2026-08-23 18:02:31.527831', '1', '60.078155755996704', '61.21489572525024', '66.19454908370972'), ('2026-08-23 18:02:31.527831', '1', '67.58205246925354', '69.01043128967285', '74.00694870948792'), ('2026-08-23 18:02:31.527831', '3', '7.511272668838501', '10.165159702301024', '15.146268129348757'), ('2026-08-23 18:02:31.527831', '3', '15.022607803344728', '18.4421911239624', '23.386617183685303'), ('2026-08-23 18:02:31.527831', '3', '37.55953645706177', '38.58948063850403', '43.59824085235596'), ('2026-08-23 18:02:31.527831', '3', '45.0730037689209', '47.38599443435669', '52.31499624252319'), ('2026-08-24 20:56:37.556662', '1', '7.525582551956177', NULL, NULL), ('2026-08-24 21:08:47.732891', '2', '7.516163110733032', '9.906562566757202', NULL), ('2026-08-24 21:11:27.611205', '2', '7.511972904205322', NULL, NULL), ('2026-08-24 21:15:33.156863', '2', '7.522573232650757', '12.997313737869264', '18.010730028152466'), ('2026-08-24 21:15:33.156863', '2', '37.5509250164032', '38.922001123428345', '43.936638832092285'), ('2026-08-24 21:15:33.156863', '2', '52.566030502319336', '53.51548886299133', '58.52410578727722'), ('2026-08-24 21:15:33.156863', '2', '82.6038773059845', '85.1386787891388', '90.1435248851776'), ('2026-08-24 21:15:33.156863', '2', '112.63368153572084', '113.9244372844696', '118.93577170372008'), ('2026-08-24 21:15:33.156863', '2', '120.14554572105408', '120.89758467674255', '125.91185998916626'), ('2026-08-24 21:15:33.156863', '1', '15.03355312347412', '16.143213987350464', '21.143581867218018'), ('2026-08-24 21:15:33.156863', '1', '60.073371171951294', '61.94524312019348', '66.93382167816162'), ('2026-08-24 21:15:33.156863', '1', '67.58504676818848', '68.861820936203', '73.77757716178894'), ('2026-08-24 21:15:33.156863', '1', '90.1123387813568', '91.98038625717165', '96.90748524665833'), ('2026-08-24 21:15:33.156863', '1', '97.61950969696044', '99.48590898513794', '104.40263772010805'), ('2026-08-24 21:15:33.156863', '3', '22.540621995925903', '115.26352858543396', '120.2697868347168'), ('2026-08-24 21:15:33.156863', '3', '30.049438953399655', '42.41787838935852', '47.361204862594604'), ('2026-08-24 21:15:33.156863', '3', '45.054606199264526', '54.6627848148346', '59.65416073799133'), ('2026-08-24 21:15:33.156863', '3', '75.09715819358826', '124.709459066391', NULL), ('2026-08-24 21:15:33.156863', '3', '105.12885475158691', '114.80560064315796', '119.77078700065611'), ('2026-08-24 21:18:00.005472', '2', '7.523841142654419', '10.437990665435793', '15.441333293914797'), ('2026-08-24 21:18:00.005472', '2', '15.037378549575806', NULL, NULL), ('2026-08-24 21:19:14.336083', '1', '37.55328321456909', '42.24522852897644', '47.24785614013672'), ('2026-08-24 21:19:14.336083', '1', '52.57439160346985', '53.89337396621704', '58.84508633613586'), ('2026-08-24 21:19:14.336083', '3', '7.523022413253784', NULL, NULL), ('2026-08-24 21:19:14.336083', '3', '15.027100086212158', NULL, NULL), ('2026-08-24 21:19:14.336083', '3', '22.529483318328857', NULL, NULL), ('2026-08-24 21:19:14.336083', '3', '30.040156602859497', NULL, NULL), ('2026-08-24 21:19:14.336083', '3', '45.064433574676514', NULL, NULL), ('2026-08-24 21:19:14.336083', '3', '60.08319592475891', NULL, NULL), ('2026-08-24 21:27:31.117281', '2', '15.032112121582031', '16.36784315109253', '21.37285017967224'), ('2026-08-24 21:27:31.117281', '3', '7.519109725952148', NULL, NULL), ('2026-08-24 21:27:31.117281', '3', '22.53892421722412', NULL, NULL), ('2026-08-24 21:29:55.878368', '2', '15.026852130889893', '19.530011653900143', '24.542566061019897'), ('2026-08-24 21:29:55.878368', '2', '52.56098484992981', '55.10469627380371', '60.11070370674133'), ('2026-08-24 21:29:55.878368', '1', '7.520529270172119', '9.256768465042114', '14.189888954162598'), ('2026-08-24 21:29:55.878368', '1', '22.534521341323853', '26.429022073745728', '31.39863586425781'), ('2026-08-24 21:29:55.878368', '1', '45.056756258010864', '46.00082850456238', '50.96085166931152'), ('2026-08-24 21:29:55.878368', '1', '60.06436014175415', NULL, NULL), ('2026-08-24 21:29:55.878368', '3', '30.044901132583615', '55.76967787742615', '60.76169276237488'), ('2026-08-24 21:29:55.878368', '3', '37.553351163864136', NULL, NULL), ('2026-08-24 21:32:33.930137', '1', '7.520627021789551', '8.448325157165527', '13.448795080184937'), ('2026-08-24 21:32:33.930137', '1', '22.538148164749146', '24.4751570224762', '29.48026967048645'), ('2026-08-24 21:32:33.930137', '1', '30.039170503616333', '39.72628569602966', NULL), ('2026-08-24 21:32:33.930137', '1', '37.54300665855408', '38.52844715118408', NULL), ('2026-08-24 21:32:33.930137', '3', '15.035158395767212', NULL, NULL), ('2026-08-24 21:36:14.711094', '2', '7.522473573684692', '11.400489807128906', '16.40607523918152'), ('2026-08-24 21:36:14.711094', '2', '15.026776313781738', '16.431926012039185', '21.438129425048828'), ('2026-08-24 21:36:14.711094', '2', '45.068030834198', '48.54012155532837', '53.54467272758484'), ('2026-08-24 21:36:14.711094', '1', '30.045210361480716', '31.18021774291992', '36.09997344017029'), ('2026-08-24 21:36:14.711094', '1', '37.559287309646606', '39.02993941307068', '43.99829649925232'), ('2026-08-24 21:36:14.711094', '1', '60.08322501182556', '61.444920778274536', NULL), ('2026-08-24 21:36:14.711094', '3', '22.53597617149353', NULL, NULL), ('2026-08-24 21:36:14.711094', '3', '52.582977056503296', NULL, NULL), ('2026-08-24 21:41:52.934078', '2', '7.517242431640625', NULL, NULL), ('2026-08-24 21:43:38.879439', '2', '22.529037475585938', '27.01321578025818', '32.02016043663025'), ('2026-08-24 21:43:38.879439', '2', '30.03486132621765', '32.34789800643921', '37.36060667037964'), ('2026-08-24 21:43:38.879439', '1', '7.512492895126343', '10.357948303222656', '15.34903645515442'), ('2026-08-24 21:43:38.879439', '1', '15.022544384002686', '16.02467131614685', '20.94684720039368'), ('2026-08-24 21:43:38.879439', '1', '37.544482707977295', '38.80655741691589', '43.80179238319397'), ('2026-08-24 21:43:38.879439', '1', '60.06664776802063', NULL, NULL), ('2026-08-24 21:43:38.879439', '3', '45.05535435676575', NULL, NULL), ('2026-08-24 21:43:38.879439', '3', '52.55709290504456', NULL, NULL), ('2026-08-24 21:48:11.830823', '2', '30.042991876602173', '31.169012308120728', '36.16997694969177'), ('2026-08-24 21:48:11.830823', '1', '7.523675680160522', '8.554848909378052', '13.54502248764038'), ('2026-08-24 21:48:11.830823', '1', '15.035255908966064', '16.604111433029175', '21.53153610229492'), ('2026-08-24 21:48:11.830823', '1', '37.55297946929932', NULL, NULL), ('2026-08-24 21:48:11.830823', '3', '22.540138006210327', NULL, NULL), ('2026-08-24 21:52:23.207655', '2', '7.523723363876343', '10.497872591018677', '15.512662649154665'), ('2026-08-24 21:52:23.207655', '2', '37.56040167808533', '39.005770206451416', NULL), ('2026-08-24 21:52:23.207655', '1', '15.032325267791748', '16.407330989837646', '21.33150053024292'), ('2026-08-24 21:52:23.207655', '1', '30.04884028434753', '32.597638845443726', '37.59100604057312'), ('2026-08-24 21:52:23.207655', '3', '22.543967485427856', NULL, NULL), ('2026-08-24 22:02:13.329518', '2', '7.512861967086792', '8.672468185424805', '13.67848253250122'), ('2026-08-24 22:02:13.329518', '2', '15.01395320892334', '16.236720085144043', '21.241623163223267'), ('2026-08-24 22:02:13.329518', '3', '22.521141052246094', '25.50180292129517', '30.45656895637512'), ('2026-08-24 22:02:13.329518', '3', '30.02299976348877', NULL, NULL), ('2026-08-24 22:02:13.329518', '3', '37.52840495109558', NULL, NULL), ('2026-08-26 16:52:20.259481', '2', '7.513665676116943', '9.339130878448486', '14.34015417098999'), ('2026-08-26 16:52:20.259481', '2', '15.022539377212524', '16.900758028030396', '21.904312133789062'), ('2026-08-26 16:53:09.797556', '2', '7.515798568725586', '9.245088577270508', '14.248880624771118'), ('2026-08-26 16:53:09.797556', '2', '15.01913571357727', '16.82163095474243', '21.835197687149048'), ('2026-08-26 16:53:09.797556', '2', '22.524407625198364', '26.313009023666385', '31.328876972198486'), ('2026-08-26 16:53:09.797556', '2', '30.02723979949951', '30.836750745773315', NULL), ('2026-08-26 18:11:40.669040', '2', '7.518483877182007', '20.59963369369507', NULL), ('2026-08-26 18:11:40.669040', '2', '15.020407438278198', '16.786518335342407', '21.802016735076904'), ('2026-08-26 18:12:58.693320', '2', '7.518507242202759', '16.670443773269653', '21.67310166358948'), ('2026-08-26 18:12:58.693320', '2', '15.027965307235718', '19.50481605529785', NULL), ('2026-08-26 18:17:20.231774', '2', '7.512979030609131', '16.620070695877075', '21.625916957855225'), ('2026-08-26 18:17:20.231774', '2', '15.02492094039917', '17.972737073898315', '22.985421180725098'), ('2026-08-26 18:17:20.231774', '2', '22.53815340995789', '24.61893129348755', '29.61954975128174'), ('2026-08-26 18:17:20.231774', '2', '30.0509250164032', '31.068912267684937', '36.08030033111572'), ('2026-08-26 18:17:20.231774', '2', '37.55594539642334', '46.20858001708984', '51.20858812332153'), ('2026-08-26 18:17:20.231774', '2', '45.065438747406006', '48.37836241722107', NULL), ('2026-08-26 18:18:31.151142', '2', '7.516880512237549', '9.219851732254028', '14.225140571594238'), ('2026-08-26 18:18:31.151142', '2', '15.029672622680664', '25.22940039634705', NULL), ('2026-08-26 18:18:31.151142', '2', '22.540918827056885', '23.93520140647888', '28.94377636909485'), ('2026-08-26 18:25:25.354407', '2', '7.522996425628662', '26.83095335960388', NULL), ('2026-08-26 18:25:25.354407', '2', '15.036287307739258', '26.495054006576535', NULL), ('2026-08-26 18:25:25.354407', '2', '22.542263507843018', '25.15896368026733', '30.17269825935364'), ('2026-08-26 18:25:25.354407', '2', '30.04939603805542', NULL, NULL), ('2026-08-26 18:29:45.107278', '2', '7.520135879516602', '18.59603261947632', '23.60466718673706'), ('2026-08-26 18:29:45.107278', '2', '15.026320457458496', '17.230756521224976', '22.240991592407227'), ('2026-08-26 18:29:45.107278', '2', '22.53667974472046', '32.889689207077026', '37.89510917663574'), ('2026-08-26 18:29:45.107278', '2', '30.03891897201538', '34.46282887458801', '39.47941875457764'), ('2026-08-26 18:29:45.107278', '2', '37.55400228500366', '38.90446138381958', NULL), ('2026-08-26 18:40:51.782899', '2', '7.525990962982178', NULL, NULL), ('2026-08-26 18:40:51.782899', '2', '15.03919529914856', NULL, NULL), ('2026-08-26 18:42:18.034917', '2', '7.523841142654419', NULL, NULL), ('2026-08-26 18:42:18.034917', '2', '15.025527238845823', NULL, NULL), ('2026-08-26 18:43:23.557365', '2', '7.522588014602661', '19.35130190849304', '24.364681720733643'), ('2026-08-26 18:43:23.557365', '2', '15.032161235809326', '17.50438356399536', '22.50731611251831'), ('2026-08-26 18:43:23.557365', '2', '22.538305282592773', '27.517093896865845', '30.04082202911377'), ('2026-08-26 18:43:23.557365', '2', '30.04082202911377', '31.611799240112305', '36.61788129806519'), ('2026-08-26 18:43:23.557365', '2', '37.54813742637634', NULL, NULL), ('2026-08-26 18:46:21.766927', '2', '7.510290145874023', '17.71462321281433', '19.69180583953857'), ('2026-08-26 18:46:21.766927', '2', '15.02385401725769', '19.69080638885498', '23.712043285369877'), ('2026-08-26 18:46:21.766927', '2', '22.535030603408813', '23.712043285369877', '28.715456247329712'), ('2026-08-26 18:46:21.766927', '2', '30.044166088104248', '31.38934874534607', '36.39010500907898'), ('2026-08-26 18:47:29.740537', '2', '7.52262020111084', '16.752413749694824', '18.236643075942997'), ('2026-08-26 18:47:29.740537', '2', '15.03128147125244', '18.236643075942997', NULL), ('2026-08-26 18:49:11.868503', '2', '7.5261194705963135', '12.993330001831056', '16.368407011032104'), ('2026-08-26 18:49:11.868503', '2', '15.031362533569336', '16.368407011032104', '21.38418650627136'), ('2026-08-26 18:49:11.868503', '2', '22.54448652267456', '31.335817575454712', '33.106365442276'), ('2026-08-26 18:49:11.868503', '2', '30.044872045516968', '33.106365442276', '38.12172222137451'), ('2026-08-26 18:49:11.868503', '2', '37.5494019985199', '39.237165212631226', '44.24010920524597'), ('2026-08-26 18:49:11.868503', '2', '45.06075716018677', '45.72534942626953', '50.72768449783325'), ('2026-08-26 18:49:11.868503', '2', '52.57396125793457', '53.39769220352173', '58.39975047111511'), ('2026-08-26 18:49:11.868503', '2', '60.07434916496277', '71.19234848022461', '76.20162868499756'), ('2026-08-26 18:49:11.868503', '2', '67.58215308189392', '69.84458136558533', '74.85265827178955'), ('2026-08-26 18:49:11.868503', '2', '75.0861656665802', '76.11576890945435', NULL), ('2026-08-26 19:00:06.508855', '2', '7.51118278503418', '26.41637372970581', NULL), ('2026-08-26 19:00:06.508855', '2', '15.015933513641356', '24.780195951461792', '29.792298316955566'), ('2026-08-26 19:00:06.508855', '2', '22.53187656402588', '27.63843536376953', NULL), ('2026-08-26 19:01:30.130975', '2', '7.51944375038147', '28.07374405860901', '31.39197087287903'), ('2026-08-26 19:01:30.130975', '2', '15.03301167488098', '24.102091789245605', '26.2808780670166'), ('2026-08-26 19:01:30.130975', '2', '22.537556886672974', '26.2808780670166', '28.07374405860901'), ('2026-08-26 19:01:30.130975', '2', '30.044751405715942', '31.39092969894409', '36.40044522285461'), ('2026-08-26 19:01:30.130975', '2', '37.55401587486267', NULL, NULL), ('2026-08-26 19:02:37.208885', '2', '7.513622760772705', '25.77759075164795', '27.108437538146973'), ('2026-08-26 19:02:37.208885', '2', '15.022539854049684', '24.034606218338013', '25.77759075164795'), ('2026-08-26 

## Post insert db sizes
<hr>
GameRun

In [15]:
after_gr_count = db.get_GameRun_count()
after_gr_count

235

In [16]:
difference = after_gr_count - before_gr_count
difference

169

PowerupsSpawned

In [17]:
after_ps_count = db.get_PowerupsSpawned_count()
after_ps_count

337

In [18]:
difference = after_ps_count - before_ps_count
difference

303